"""
daily_log.py — Writes a daily log entry and commits it to git.
Usage: python3 daily_log.py
Schedule it with cron to run automatically every day.

Cron example (runs daily at 9am):
  crontab -e
  0 9 * * * cd /Users/wilson.chisessu/Documents/ai_test && python3 daily_log.py
"""

import json
import os
import subprocess
from datetime import datetime

LOGS_DIR = "logs"
PROFILE_FILE = "profile.json"


def load_profile():
    if os.path.exists(PROFILE_FILE):
        with open(PROFILE_FILE) as f:
            return json.load(f)
    return {}


def get_git_stats():
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "-5"],
            capture_output=True, text=True
        )
        return result.stdout.strip() or "No recent commits."
    except Exception:
        return "Git stats unavailable."


def write_log(entry):
    os.makedirs(LOGS_DIR, exist_ok=True)
    today = datetime.now().strftime("%Y-%m-%d")
    log_file = os.path.join(LOGS_DIR, f"{today}.md")

    with open(log_file, "w") as f:
        f.write(entry)

    print(f"Log written: {log_file}")
    return log_file


def git_commit(log_file):
    today = datetime.now().strftime("%Y-%m-%d")
    try:
        subprocess.run(["git", "add", log_file], check=True)
        subprocess.run(
            ["git", "commit", "-m", f"Daily log: {today}"],
            check=True
        )
        subprocess.run(["git", "push", "origin", "main"], check=True)
        print("Committed and pushed to GitHub.")
    except subprocess.CalledProcessError as e:
        print(f"Git error: {e}")


def build_entry(profile):
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M:%S")
    git_stats = get_git_stats()

    return f"""# Daily Log — {date_str}

**Engineer:** {profile.get('name', 'Wilson Chisessu')}
**Role:** {profile.get('role', 'IT Systems Engineer')}
**Location:** {profile.get('location', 'Cape Town, South Africa')}
**Logged at:** {time_str}

---

## Activity Summary

- Daily log auto-generated at {time_str}

## Recent Commits

```
{git_stats}
```

## Notes

_Add your notes for today here._

---
*Auto-generated by daily_log.py*
"""


def main():
    profile = load_profile()
    entry = build_entry(profile)

    print("\n--- Daily Log Preview ---\n")
    print(entry)

    save = input("Save and push to GitHub? (yes/no): ").strip().lower()
    if save in ["yes", "y"]:
        log_file = write_log(entry)
        git_commit(log_file)
    else:
        print("Log discarded.")


if __name__ == "__main__":
    main()
